# Generated by Django 6.1.1 on 2026-09-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('aluno', 'Aluno')], default='aluno', max_length=10),
        ),
    ]
