# Generated by Django 6.1.1 on 2026-09-12 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modulo', models.CharField(max_length=100)),
                ('descricao_modulo', models.TextField()),
                ('ordem_modulo', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_conteudo', models.CharField(max_length=150)),
                ('explicacao_conteudo', models.TextField()),
                ('ordem_conteudo', models.PositiveIntegerField(default=0)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='modulos.modulo')),
            ],
        ),
    ]
