# Generated by Django 6.1.1 on 2026-09-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteudomodulo',
            options={'verbose_name': 'Conteúdo', 'verbose_name_plural': 'Conteúdos dos Módulos'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos de Aprendizagem'},
        ),
    ]
